// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxbfgennjhmsoglrcuwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4YmZnZW5uamhtc29nbHJjdXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQzNjQ5NDYsImV4cCI6MjA0OTk0MDk0Nn0.bRvGWFBpE09pibATmSY1XPvjw0HT7b57VRDmTP58e7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);